### ISSUE TITLE
Not clear as where is the stopwatch?

### ISSUE THREAD

**Issue by shadowbq** [deltaidea/atom-stopwatch#7]
README does not provide a clear way to identify where this stop watch might be..

Status bar?

There is no setting or keybinding to show it..

**Comment by deltaidea** [comment]
Sorry, didn't have enough time to document it all.

Please refer to this screenshot meanwhile:

![image](https://cloud.githubusercontent.com/assets/4950036/9339699/f032c7d4-4604-11e5-9c71-5aa7ffb64ada.png)

Hope that answers your question. :)

**Comment by shadowbq** [comment]
:+1:
